/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PlaygroundButton {
        "text": string;
    }
}
declare global {
    interface HTMLPlaygroundButtonElement extends Components.PlaygroundButton, HTMLStencilElement {
    }
    var HTMLPlaygroundButtonElement: {
        prototype: HTMLPlaygroundButtonElement;
        new (): HTMLPlaygroundButtonElement;
    };
    interface HTMLElementTagNameMap {
        "playground-button": HTMLPlaygroundButtonElement;
    }
}
declare namespace LocalJSX {
    interface PlaygroundButton {
        "text"?: string;
    }
    interface IntrinsicElements {
        "playground-button": PlaygroundButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "playground-button": LocalJSX.PlaygroundButton & JSXBase.HTMLAttributes<HTMLPlaygroundButtonElement>;
        }
    }
}
